language: go
matrix:
  include:
    - go: 1.12.x
      os: linux
      env: GO111MODULE=on
      after_success:
        - codecov
    - go: master
      os: linux
      env: GO111MODULE=on
    - go: 1.12.x
      os: osx
      env: GO111MODULE=on
    - go: master
      os: osx
      env: GO111MODULE=on
    - go: 1.12.x
      os: windows
      env:
        - GO111MODULE=on
      before_install:
        - echo $TRAVIS_GO_VERSION
        - echo $TERM
      script:
        - go test -v
    - go: master
      os: windows
      env:
        - GO111MODULE=on
      before_install:
        - echo $TRAVIS_GO_VERSION
        - echo $TERM
      script:
        - go test -v
      after_script:
        - ps aux
  allow_failures:
    - go: master
before_install:
  - echo $TRAVIS_GO_VERSION
  - echo $TERM
  - sudo pip install codecov
script:
  - make ci
