language: go
matrix:
  include:
    - go: 1.12.x
      os: linux
    - go: master
      os: linux
    - go: 1.12.x
      os: osx
    - go: master
      os: osx
  allow_failures:
    - go: master
env: GO111MODULE=on
install:
  - echo $TRAVIS_GO_VERSION
  - sudo pip install codecov
script:
  - make ci
after_script:
  - codecov
