name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
  windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        go_version: [1.17]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
